// Anything exported under this directory that will be used outside of this directory will be exported from here

// customer
import {
  logOutCustomer,
  setCustomer,
  setEvents,
  addMessage,
  updateLastMessage,
  addOrganizedMeetings,
  addConversation,
  addCPinnedChat,
  removeCPinnedChat,
  addCComment,
  resetState,
} from "./customer/customerSlice";
import {
  createCustomer,
  customerForGetPassword,
  getEvents,
  loginCustomer,
  getConversations,
  getMessages,
  getCustomerMeetings,
  addCBio,
  addCCountry,
  addCCity,
  getCMeetings,
  uploadCImage,
  searchCUser,
  createCDiscussionForum,
  getCDiscussionForums,
  getCDiscussionForumDetail,
  getCReminders,
  getCCaseManager,
} from "./customer/api";
// manager
import {
  logOutManager,
  setManager,
  addMMessage,
  mUpdateLastMessage,
  setMConversations,
  addMConversation,
  addMPinnedChat,
  removeMPinnedChat,
  addRemindersIntoState,
  resetMState,
} from "./manager/managerSlice";
// common
import type { AppDispatchType, RootStateType } from "./store";
import {
  updateRole,
  resetRole,
  toggleTabBar,
  setAddChatConversationId,
  setTokenSent,
  setInCallState,
  setIsOnCallScreen,
  setCallObjectState
} from "./common/uiSlice";
import { sendDeviceToken } from "./common/api";
import {
  createManager,
  forGetPassword,
  loginManager,
  getCustomers,
  createMeeting,
  getManagerMeetings,
  getInitialManagerMeetings,
  getMConversations,
  getMMessages,
  uploadMImage,
  addMBio,
  addMSpecialization,
  addMCountry,
  addMCity,
  getMReminders,
  createReminders,
  inviteCustomerIntoReminders,
  getLinkedCustomers,
} from "./manager/api";

export {
  setEvents,
  logOutCustomer,
  setCustomer,
  logOutManager,
  setManager,
  updateRole,
  createCustomer,
  customerForGetPassword,
  getEvents,
  loginCustomer,
  resetRole,
  toggleTabBar,
  addMessage,
  getConversations,
  getMessages,
  updateLastMessage,
  createManager,
  forGetPassword,
  loginManager,
  getCustomers,
  createMeeting,
  getManagerMeetings,
  getCustomerMeetings,
  getInitialManagerMeetings,
  getMConversations,
  getMMessages,
  addMMessage,
  mUpdateLastMessage,
  addOrganizedMeetings,
  setMConversations,
  uploadMImage,
  addMBio,
  addMSpecialization,
  addMCountry,
  addMCity,
  addCBio,
  addCCountry,
  addCCity,
  getCMeetings,
  uploadCImage,
  searchCUser,
  setAddChatConversationId,
  addConversation,
  addMConversation,
  addMPinnedChat,
  removeMPinnedChat,
  addCPinnedChat,
  removeCPinnedChat,
  createCDiscussionForum,
  getCDiscussionForums,
  addCComment,
  getCDiscussionForumDetail,
  sendDeviceToken,
  setTokenSent,
  getCReminders,
  getMReminders,
  createReminders,
  inviteCustomerIntoReminders,
  addRemindersIntoState,
  getCCaseManager,
  getLinkedCustomers,
  resetState,
  resetMState,
  setInCallState,
  setIsOnCallScreen,
  setCallObjectState,
  type AppDispatchType,
  type RootStateType,
};
